"""
solitaire_constants.py 
Author: Robert Pal
Updated: 2025-09-21

This module contains all constant configurations for the solitaire gui application.
"""

# Window Configuration
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 1000
WINDOW_TITLE = "Solitaire - Emoji Edition"
 
# Colors
BG_COLOR = "#006400"  # Dark green felt color
BG_COLOR_TEST = "#640032"  # Test color
FOUNDATION_BG_COLOR = "#004d00"
TEXT_COLOR_DEFAULT = "white"
TEXT_COLOR_RED = "red"
TEXT_COLOR_BLACK = "black"
 
# Fonts
FONT_FAMILY = "Arial"
FONT_SIZE_RESET = 22
FONT_SIZE_STOCK_SMALL = 36
FONT_SIZE_STOCK_LARGE = 48
FONT_SIZE_FOUNDATION = 28
FONT_SIZE_TABLEAU_LARGE = 32
FONT_SIZE_TABLEAU_SMALL = 22
 
# Padding & Layout
PAD_TOP_FRAME = (20, 0)
PAD_STOCK_WASTE_X = 10
PAD_STOCK_WASTE_Y = (10, 0)
PAD_FOUNDATION = 10
PAD_TABLEAU_X = 10
PAD_TABLEAU_Y = 0
PAD_TABLEAU_Y_ANCHOR = "n"
 
# Foundation Piles
FOUNDATION_WIDTH = 3
FOUNDATION_HEIGHT = 2
FOUNDATION_COUNT = 4
FOUNDATION_RELIEF = "groove"
FOUNDATION_BORDERWIDTH = 2
 
# Tableau Piles
TABLEAU_COUNT = 7
TABLEAU_PILE_WIDTH = 140
TABLEAU_PAD_Y = 20
 
# Card Selection UI
CARD_SELECTED_RELIEF = "sunken"
CARD_SELECTED_BORDERWIDTH = 2
CARD_DEFAULT_RELIEF = "flat"
 
# Font Size Thresholds
TABLEAU_SIZE_THRESHOLD = 15
 
# Suit Color Map
SUIT_BLACK = {"S", "C"}

# Window Configuration
SOLITAIRE_WINDOW_WIDTH = 1200
SOLITAIRE_WINDOW_HEIGHT = 1000
SOLITAIRE_WINDOW_TITLE = "Solitaire - Emoji Edition"

# Colors
SOLITAIRE_BG_COLOR = "#006400"  # Dark green felt color
SOLITAIRE_BG_COLOR_TEST = "#640032"  # Test color
SOLITAIRE_FOUNDATION_BG_COLOR = "#004d00"
SOLITAIRE_TEXT_COLOR_DEFAULT = "white"
SOLITAIRE_TEXT_COLOR_RED = "red"
SOLITAIRE_TEXT_COLOR_BLACK = "black"

# Fonts
SOLITAIRE_FONT_FAMILY = "Arial"
SOLITAIRE_FONT_SIZE_RESET = 22
SOLITAIRE_FONT_SIZE_STOCK_SMALL = 36
SOLITAIRE_FONT_SIZE_STOCK_LARGE = 48
SOLITAIRE_FONT_SIZE_FOUNDATION = 28
SOLITAIRE_FONT_SIZE_TABLEAU_LARGE = 32
SOLITAIRE_FONT_SIZE_TABLEAU_SMALL = 22

# Padding & Layout
SOLITAIRE_PAD_TOP_FRAME = (20, 0)
SOLITAIRE_PAD_STOCK_WASTE = 10
SOLITAIRE_PAD_STOCK_Y = (10, 0)
SOLITAIRE_PAD_FOUNDATION = 10
SOLITAIRE_PAD_TABLEAU_X = 10
SOLITAIRE_PAD_TABLEAU_Y = 0
SOLITAIRE_PAD_TABLEAU_Y_ANCHOR = "n"

# Foundation Piles
SOLITAIRE_FOUNDATION_WIDTH = 3
SOLITAIRE_FOUNDATION_HEIGHT = 2
SOLITAIRE_FOUNDATION_COUNT = 4
SOLITAIRE_FOUNDATION_RELIEF = "groove"
SOLITAIRE_FOUNDATION_BORDERWIDTH = 2

# Tableau Piles
SOLITAIRE_TABLEAU_COUNT = 7
SOLITAIRE_TABLEAU_PILE_WIDTH = 140
SOLITAIRE_TABLEAU_PAD_Y = 20

# Card Selection UI
SOLITAIRE_CARD_SELECTED_RELIEF = "sunken"
SOLITAIRE_CARD_SELECTED_BORDERWIDTH = 2
SOLITAIRE_CARD_DEFAULT_RELIEF = "flat"

# Font Size Thresholds
SOLITAIRE_TABLEAU_SIZE_THRESHOLD = 15

# Suit Color Map
SOLITAIRE_SUIT_BLACK = {"S", "C"}